### PR TITLE
Upgrade to latest nan

### PR DESCRIPTION
**Pull request by bobrippling**
This upgrades the `nan` dependency of this module, upgrading parts of the code which were still using specific node APIs (which aren't stable).

There are also a few (Objective-)C++ tweaks too.

### CODE REVIEW

**Comment by lukeapage** [comment]
@poiru since you created this package for us, please could you either merge and publish or else give me and/or Rob permission to publish the npm package and we will publish and change the repo url.

**Comment by lukeapage** [comment]
Thanks @poiru ! 

For npm my username is lukeapage

**Comment by poiru** [comment]
@lukeapage Merged and published as `osx-mouse-cocoa@1.0.3`!

**Comment by poiru** [comment]
@lukeapage @bobrippling Also added you as owners of this repo and the npm package, feel free to merge/publish going forward.

**Pull request merged**
